//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Food()
        {
            this.Assigneds = new HashSet<Assigned>();
        }
    
        public int FoodID { get; set; }
        public Nullable<int> RID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Assigned> Assigneds { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
